apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  type: LoadBalancer
  selector:
    app: sistema-noticias
  ports:
    - port: 80
      #targetPort: 80
      nodePort: 30001
  